#ifndef CONFIG_SET
#define CONFIG_SET

////////OLED OPTIONS////////
#define OLED_BRIGHTNESS			128
#define OLED_VISIBLE_PIXEL_WIDTH	128
#define OLED_VISIBLE_PIXEL_HEIGHT	32
#define OLED_CHAR_WIDTH			5
#define OLED_CHAR_HEIGHT		7 //UNUSED FOR NOW
#define OLED_CHAR_X_PADDING		1
#define OLED_X_DEADSPACE		4
#define OLED_Y_DEADSPACE		0
#define OLED_FONT_MEM_OFFSET		0//768

#define OLED_CHAR_COLS		(OLED_VISIBLE_PIXEL_WIDTH/(OLED_CHAR_WIDTH+OLED_CHAR_X_PADDING))
#define OLED_CHAR_ROWS		(OLED_VISIBLE_PIXEL_HEIGHT/OLED_CHAR_HEIGHT)
#define OLED_PIXEL_WIDTH	(OLED_VISIBLE_PIXEL_WIDTH+OLED_X_DEADSPACE)

////////THREAD OPTIONS////////
#define TCB_LEN 8
#define STACK_WORD_SIZE (128)
#define SYSTICKS_PER_SECOND 2000


////////CONSTANT CALCULATIONS////////
#define CLK_SPEED 72000000
#define SYSTICK_SPEED (CLK_SPEED/8)
#define SYSTICK_COUNTER SYSTICK_SPEED/SYSTICKS_PER_SECOND
#define SYSTICK_RELOAD (SYSTICK_COUNTER-1)
#define SYSTICKS_PER_MS SYSTICKS_PER_SECOND/1000


#endif
