
#ifndef CONFIG_SET

#define CONFIG_SET

#define TCB_LEN 8
#define STACK_WORD_SIZE (156)
#define BRIGHTNESS 128

#define CLK_SPEED 72000000
#define SYSTICK_SPEED (CLK_SPEED/8)

#define SYSTICKS_PER_SECOND 2000


#define SYSTICK_COUNTER SYSTICK_SPEED/SYSTICKS_PER_SECOND
#define SYSTICK_RELOAD (SYSTICK_COUNTER-1)

#define SYSTICKS_PER_MS SYSTICKS_PER_SECOND/1000


#endif
